### ISSUE TITLE
data

### ISSUE THREAD

**Issue by tantantan007** [ai-med/DiaMond#1]
打扰，能说明一下数据怎么制作吗，或者上传数据的代码，我手上有nii的配对数据，还有一个问题，两个单模态的数据经过linear层后，regbn之前，特征尺寸变成多少了呢，似乎regbn处理三维或者二维数据显存要求很大

**Comment by Yiiitong** [comment]
Hi,

Thanks for the questions. For the creation of hdf5 dataset, you can refer to the official tutorial here: https://docs.h5py.org/en/stable/high/dataset.html, so that the data follow a hierarchical format with its ID as the group name, including the following entries:

- A group named MRI/T1, containing the T1-weighted 3D MRI data.
- A group named PET/FDG, containing the 3D FDG PET data.
- A string attribute DX containing the diagnosis labels: CN, Dementia/AD, FTD, or MCI, if available.
- A scalar attribute RID with the patient ID, if available.

After the linear layer and before RegBN, the dimension of the features for the individual modality becomes 128 for 2-class classification, and 192 for 3-class classification. RegBN indeed requires large memory for processing whole 2D/3D input, thus we use it on the latent features in the late stage to save memory.

**Comment by tantantan007** [comment]
Thank you for your reply. Could you upload two data samples? It seems I was not successful in creating them.
